### ISSUE TITLE
Add event model

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#10]
Implement the `event` model class. Be sure to take a look at the [Models Wiki](https://github.com/iiitv/club_calender/wiki/Models) to get a better idea of how these models should look like and how they'd be used.

**Comment by vikiwarrior** [comment]
I would like to work on this issue

**Comment by thecodepapaya** [comment]
GFI @vikiwarrior

**Comment by thecodepapaya** [comment]
@vikiwarrior do we have an update on this issue?

**Comment by vikiwarrior** [comment]
Please review my PR
