### ISSUE TITLE
Add attendee model class

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#11]
implement the `attendee` model class.

**Comment by Chirag-Mathur** [comment]
@thecodepapaya what type of functionalities do we have to add in it ?

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers i would like to work on this issue.

**Comment by yashshah2820** [comment]
@Chirag-Mathur GFI 👍

**Comment by thecodepapaya** [comment]
Be sure to take a look at the [Models Wiki](https://github.com/iiitv/club_calender/wiki/Models) to get a better idea of how these models should look like and how they'd be used.
