### ISSUE TITLE
Add travis

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#2]
Integrate the [Travis-CI](https://travis-ci.org/) service along with a smoke test. 
- If you haven't heard about smoke testing before, then take a look at these articles [1](https://www.guru99.com/smoke-testing.html), [2](https://softwaretestingfundamentals.com/smoke-testing/)
- For writing test in Flutter, take a look [here](https://flutter.dev/docs/cookbook/testing/unit/introduction)

**Comment by vidit2512** [comment]
@iiitv/project-maintainers I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @vidit2512

**Comment by vidit2512** [comment]
@iiitv/project-maintainers I have a doubt .I want to ask you that whether I have to make  2 files(travis.yml and  test.dart) or anything else?
My another query is that if test.dart I have to do testing for various units which will vary depending upon the features added in the project. So for how many units I have to make testing file?

**Comment by thecodepapaya** [comment]
> whether I have to make 2 files(travis.yml and test.dart) or anything else?

Yes, you only have to make two files. Add the `.travis.yml` and replace the `widget_test.dart` inside test folder with a file named something like `app_test.dart`. Remember the file name could be anything but it must end with `_test.dart`.

> So for how many units I have to make testing file?

You don't have to add unit tests now. They would be added in a separate issue. You just have to add one smoke test to make sure that the application compiles.

Take a look at [this repository](https://github.com/yjbanov/flutter_travis_sample) for sample code. It should give you a better understanding of the [Travis configuration file](https://github.com/yjbanov/flutter_travis_sample/blob/master/.travis.yml) and [test file](https://github.com/yjbanov/flutter_travis_sample/blob/master/test/app_test.dart).

**Comment by vidit2512** [comment]
@thecodepapaya thanks! 
Yeah, I am taking help from that link only to get better understanding.😁😅

**Comment by anshumanv** [comment]
Use GitHub Actions?
