### ISSUE TITLE
Create login screen UI

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#3]
Create the login screen UI by taking cues from the project [Wiki](https://github.com/iiitv/club_calender/wiki/UI-design-guidelines). You are free to make adaptation and improve the designs as you see fit.

**Note**: This issue is only related to the UI implementation part and does not deal with the functionality part. The actual login functionality would be implemented in a separate issue.

**Comment by Monik09** [comment]
@thecodepapaya I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Monik09

**Comment by Monik09** [comment]
@thecodepapaya Should I add textfields for input in this page or we have to create another page for this?

**Comment by thecodepapaya** [comment]
No, the design for this page would be very simple and consist of only 3 elements, the app logo, app name and a button. You can take a look the updated [Design Wiki](https://github.com/iiitv/club_calender/wiki/UI-design-guidelines#login-screen). However, you are free to choose the color schemes you prefer. Be sure to polish the components so that they look nice 🤩 and add a screenshot of the design in your PR ✌
