### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#4]
Update the README with all the necessary information required for building this project. The README must include at least the following

- Instruction to clone and setup the environment
- Instruction to build the project
- Relevant project badges
- Add relevant link

You may take a look at the README of other repositories for inspiration.

**Comment by nlok5923** [comment]
@thecodepapaya i would like to work on this issue.

**Comment by Monik09** [comment]
@iiitv/project-maintainers  I want to work on this issue.

**Comment by yashshah2820** [comment]
@Monik09 you already have to issues assigned to you at present

**Comment by Monik09** [comment]
@iiitv/project-maintainers now I have only one issue, if it seems good so can I work on this.

**Comment by thecodepapaya** [comment]
GFI @Monik09

**Comment by Monik09** [comment]
@iiitv/project-maintainers  as of now, there are no badges yet so should I give the heading and keep the space empty for it or should not write the heading for it?

**Comment by thecodepapaya** [comment]
You can keep the space empty for now
