### ISSUE TITLE
Implement Google Sign-in functionality

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#6]
Implement Google sign-in functionality. You'd need the access to the Firebase project to implement this functionality.
Request for access on #1.
This issue is currently blocked by #3

**Comment by thecodepapaya** [comment]
Since #3 is closed now, this issue is up for grabs now.

**Comment by Monik09** [comment]
@iiitv/project-maintainers I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Monik09

**Comment by Monik09** [comment]
@thecodepapaya Sir, when I was checking the Google sign-in option, flutter was giving an error:
 `PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)`
and when I searched for that and got the solution (https://github.com/flutter/flutter/issues/33393) to save the OAuth Consent screen but in our project, it is saying verification not required.

![image](https://user-images.githubusercontent.com/52850691/92254157-13cc3a80-eeee-11ea-90d1-dcc1cb327e58.png)
After changing to internal also, I am getting this error.
Can you please tell me where I am missing any step.

**Comment by thecodepapaya** [comment]
Use [keytool](https://stackoverflow.com/a/15727931/10505839) to get your debug SHA-1 certificate fingerprint and add it to the app settings in the firebase project.
