### ISSUE TITLE
Update app launcher icon

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#7]
Update the default launcher icon of the app.
This [package](https://pub.dev/packages/flutter_launcher_icons) could come in handy.

**Comment by Monik09** [comment]
@thecodepapaya I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Monik09

**Comment by Monik09** [comment]
@thecodepapaya do I need to use any previous icon or a new icon for it?

**Comment by thecodepapaya** [comment]
You can use the club logo for now but if you'd like to come up with something new or better then that's fine as well.
