### ISSUE TITLE
Organize files in the UI folder

### ISSUE THREAD

**Issue by AkhileshManda** [iiitv/club_calender#70]
### I understand and confirm the below statements

- [ x] I have read the [Wiki](https://github.com/iiitv/club_calender/wiki) and I understand the concept and structure of the app.
- [ x] The functionality has not already been covered in an existing issue.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x ] I understand that I will be unassigned from this issue if I fail to send a PR for this within 3 days.

I think the below manner is a better way to organize the files in the UI folder
![image](https://user-images.githubusercontent.com/70640191/139224569-fce38e5e-4da5-4c03-af69-a231bbb7fa02.png)

**Comment by AkhileshManda** [comment]
@iiitv/flutter-maintainers

**Comment by vikiwarrior** [comment]
yep go ahead @AkhileshManda
