### ISSUE TITLE
Add organizer model

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calender#9]
implement the `organizer` model class.

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers I want to work on this issue

**Comment by yashshah2820** [comment]
@Chirag-Mathur  GFI 👍

**Comment by thecodepapaya** [comment]
Be sure to take a look at the [Models Wiki](https://github.com/iiitv/club_calender/wiki/Models) to get a better idea of how these models should look like and how they'd be used.

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers Do we have to add only the attributes associated in the model class?

**Comment by thecodepapaya** [comment]
For now, just add the attributes. We'd also have to add helper methods for converting data to/from Firebase but that would be handled in a separate issue.
